name: Go
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: dep
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        go get -u github.com/gordonklaus/ineffassign

    - name: lint
      run: | 
        export PATH=$PATH:$(go env GOPATH)/bin
        ./lint.sh

    - name: test
      run: go test -race -cover -v
